name: Fuzz Parser

on:
  pull_request:
    branches: [master]
    paths:
      - src/scanner.c
      - src/unicode.h
      - src/**/*.h
  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run fuzzer
        uses: tree-sitter/fuzz-action@v4
